services:
  - type: web
    name: kakoytokursach2
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: kakoytokursach2
          property: host
      - key: SKIP_ESLINT
        value: true
    autoDeploy: true 